version: '3.8'

services:
  anime-db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ../resources/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
